Repository NovaMods/nova-rs, pull requests merged in 2019-07, with the labels that each got.

#5 Add the API-agnostic RHI traits, structs, and enums
  Cargo.toml
  docs/faq.md
  docs/project_charter.md
  src/lib.rs
  src/rhi/mod.rs
  src/rhi/rhi_enums.rs
  src/rhi/rhi_structs.rs
  src/rhi/rhi_traits.rs
  src/rhi/vulkan/vulkan_graphics_api.rs
  src/rhi/vulkan/vulkan_physical_device.rs
  src/shaderpack/shaderpack_data.rs
  tools/git-hooks/hooks-revision
Labels: enhancement

#12 Add fmt check to pre-commit check
  build.rs
  tools/git-hooks/hooks-revision
  tools/git-hooks/pre-commit
Labels: enhancement

#13 Add README and other documentation
  README.md
  docs/contributing.md
  docs/images/nova-logo-128px-noborder.png
  docs/images/nova-logo-256px.png
  docs/rust_faq.md
Labels: documentation

#15 [rhi] Add missing &self and a newline
  src/rhi/rhi_enums.rs
  src/rhi/rhi_traits.rs
  tools/git-hooks/hooks-revision
Labels: bug

#18 Add Various Convention Docs
  docs/contributing.md
  docs/git.md
  docs/project_pipeline.md
  docs/rust_conventions.md
Labels: documentation

#25 [rhi] Fix clippy warnings
  src/rhi/rhi_enums.rs
  src/rhi/rhi_traits.rs
Labels: enhancement

#26 Repeatable Builds
  .appveyor.yml
  .gitignore
  .nova-root
  .travis.yml
  Cargo.lock
  README.md
  rust-toolchain
  src/shaderpack/shaderpack_data.rs
  tools/update/main.py
  update.py
Labels: enhancement

#27 Preparation for Filesystem
  .appveyor.yml
  .travis.yml
  Cargo.lock
  Cargo.toml
  docs/git.md
  src/core/mod.rs
  src/core/reactor/mod.rs
  src/core/reactor/multi_thread.rs
  src/core/reactor/single_thread.rs
  src/fs/dir.rs
  src/fs/file.rs
  src/fs/mod.rs
  src/lib.rs
  src/loading/dir/iter.rs
  src/loading/dir/mod.rs
  src/loading/dir/reactor.rs
  src/loading/mod.rs
  src/shaderpack/mod.rs
  src/shaderpack/shaderpack_data.rs
  tools/git-hooks/commit-msg
  tools/git-hooks/hooks-revision
  tools/update/main.py
  update.py
Labels: enhancement

#28 Documentation Sprint
  src/debugging/mod.rs
  src/fs/dir.rs
  src/fs/file.rs
  src/lib.rs
  src/loading/dir/iter.rs
  src/loading/mod.rs
  src/logging/mod.rs
  src/rhi/mod.rs
  src/rhi/rhi_enums.rs
  src/rhi/rhi_structs.rs
  src/rhi/rhi_traits.rs
  src/rhi/vulkan/vulkan_graphics_api.rs
  src/settings/mod.rs
  src/shaderpack/mod.rs
  src/surface/mod.rs
Labels: documentation, enhancement
